### ISSUE TITLE
[Bug] Collision detection is not working when reveal effect is "scale up"

### ISSUE THREAD

**Issue by sanek184** [emvaized/selecton-extension#44] opened 2022-10-18 10:35 UTC
over the edge
![screenshot 17424](https://user-images.githubusercontent.com/10418650/196408037-0884ae68-9544-48ed-bd2b-ed49ea60d25c.jpg)

**Comment by emvaized** [comment] 2022-10-18 13:10
What is the URL of page, which you're facing this issue on?

**Comment by sanek184** [comment] 2022-10-18 13:13
> 

This happens on any page where the selection is close to the edge. Vivaldi Browser

**Comment by emvaized** [comment] 2022-10-18 13:45
Did this issue emerged after recent updating to 3.6.7, or was present in previous versions as well?

**Comment by emvaized** [comment] 2022-10-19 22:49
Does this issue still happen in the new version 3.6.8?

**Comment by emvaized** [comment] 2022-10-25 19:22
Your issue most likely was caused by faulty 3.6.7 version, which caused tooltip to malfunction. 
As for now, I can not see any problems with collision detection in Vivaldi: 
<img width="286" alt="screenshot" src="https://user-images.githubusercontent.com/37851576/197863089-f4ebd233-d60b-4fe1-962b-c16414f03759.png">

Closing this issue as resolved now – please feel free to reopen if you're still facing the collision problem after latest update.

**Comment by sanek184** [comment] 2022-10-26 04:50
![screenshot 17465](https://user-images.githubusercontent.com/10418650/197937552-566df6f5-2a9b-4139-9e41-22dc347e0d08.jpg)
![screenshot 17466](https://user-images.githubusercontent.com/10418650/197937559-f8813324-d04c-42db-be1c-87f6d2ddd2df.jpg)
![screenshot 17467](https://user-images.githubusercontent.com/10418650/197937565-0a41994e-eceb-4cea-83f9-a1c7eda8fe82.jpg)

**Comment by sanek184** [comment] 2022-10-26 04:56
I reinstalled the extension - the problem went away. Then I will reconfigure it, because when you restore the settings, the problem reappears

**Comment by emvaized** [comment] 2022-10-26 21:11
Hm... Than, it's a bug with "scale up" effect. Thanks, I'll take a look at this

**Comment by emvaized** [comment] 2022-12-05 00:53
Fix for this problem landed in new version 3.6.9

**Closed by emvaized** 2022-12-05 00:53 UTC
Labels: bug
